name: Validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    runs-on: ubuntu-18.04
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set PubMatic enterprise GitHub User
      uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'pm-openwrap-cicd'
        email: 'pm-openwrap-cicd@pubmatic.com'
        actor: 'pm-openwrap-cicd'
        token: '${{ secrets.PM_OPENWRAP_CICD_PASSWORD }}'

    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        # Resolves to empty string for push events and falls back to HEAD.
        # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Validate
      run: |
        ./validate.sh --nofmt
      env:
        GO111MODULE: "on"
        GOPRIVATE: "git.pubmatic.com/PubMatic/*"
