name: Validate Merge

on:
  pull_request:
    branches: [master]

jobs:
  validate-merge:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Checkout Merged Branch
      uses: actions/checkout@v2

    - name: Set PubMatic enterprise GitHub User
      uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'pm-openwrap-cicd'
        email: 'pm-openwrap-cicd@pubmatic.com'
        actor: 'pm-openwrap-cicd'
        token: '${{ secrets.PM_OPENWRAP_CICD_PASSWORD }}'

    - name: Validate
      run: |
        ./validate.sh --nofmt
      env:
        GO111MODULE: "on"
        GOPRIVATE: "git.pubmatic.com/PubMatic/*"
